# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Awesome Bda"
license = "MIT"
licenselink = "https://github.com/Hebilicious/awesome-bda/blob/master/LICENSE.md"
description = "Blackderanalytics hugo theme."
homepage = "http://siteforthistheme.com/"
tags = [hugo, webpack, bootstrap]
min_version = "0.20"

[author]
  name = "Hebilicious"
  homepage = "https://github.com/Hebilicious"
